export const GET_ADD_ING = 'GET_ADD_ING';
export const GET_ADD_SUCCESS = 'GET_ADD_SUCCESS';
export const GET_ADD_FAIL = 'GET_ADD_FAIL';

export const GET_NEWFEED_ING = 'GET_NEWFEED_ING';
export const GET_NEWFEED_SUCCESS = 'GET_NEWFEED_SUCCESS';
export const GET_NEWFEED_FAIL = 'GET_NEWFEED_FAIL';

export const POST_NEWFEED_ING = 'POST_NEWFEED_ING';
export const POST_NEWFEED_SUCCESS = 'POST_NEWFEED_SUCCESS';
export const POST_NEWFEED_FAIL = 'POST_NEWFEED_FAIL';
