export const GET_ADD_ING = 'GET_ADD_ING';
export const GET_ADD_SUCCESS = 'GET_ADD_SUCCESS';
export const GET_ADD_FAIL = 'GET_ADD_FAIL';

export const GET_ADD_SEARCH_ING = 'GET_ADD_SEARCH_ING';
export const GET_ADD_SEARCH_SUCCESS = 'GET_ADD_SEARCH_SUCCESS';
export const GET_ADD_SEARCH_FAIL = 'GET_ADD_SEARCH_FAIL';

export const GET_NEWFEED_ING = 'GET_NEWFEED_ING';
export const GET_NEWFEED_SUCCESS = 'GET_NEWFEED_SUCCESS';
export const GET_NEWFEED_FAIL = 'GET_NEWFEED_FAIL';

export const GET_USERFACEBOOK_ING = 'GET_USERFACEBOOK_ING';
export const GET_USERFACEBOOK_SUCCESS = 'GET_USERFACEBOOK_SUCCESS';
export const GET_USERFACEBOOK_FAIL = 'GET_USERFACEBOOK_FAIL';

export const GET_USER_ING = 'GET_USER_ING';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';

export const GET_SEARCHUSER_ING = 'GET_SEARCHUSER_ING';
export const GET_SEARCHUSER_SUCCESS = 'GET_SEARCHUSER_SUCCESS';
export const GET_SEARCHUSER_FAIL = 'GET_SEARCHUSER_FAIL';

export const POST_NEWFEED_ING = 'POST_NEWFEED_ING';
export const POST_NEWFEED_SUCCESS = 'POST_NEWFEED_SUCCESS';
export const POST_NEWFEED_FAIL = 'POST_NEWFEED_FAIL';

export const GET_HOMEDETAIL_ING = 'GET_HOMEDETAIL_ING';
export const GET_HOMEDETAIL_SUCCESS = 'GET_HOMEDETAIL_SUCCESS';
export const GET_HOMEDETAIL_FAIL = 'GET_HOMEDETAIL_FAIL';

export const GET_POSITION_SUCCESS = 'GET_POSITION_SUCCESS';
export const GET_POSITION_FAIL = 'GET_POSITION_FAIL';
export const SET_USER = 'SET_USER';
export const SET_USER_DATABASE = 'SET_USER_DATABASE';

export const GET_USERDETAIL_ING = 'GET_USERDETAIL_ING';
export const GET_USERDETAIL_SUCCESS = 'GET_USERDETAIL_SUCCESS';
export const GET_USERDETAIL_FAIL = 'GET_USERDETAIL_FAIL';

export const GET_PLACEDETAIL_ING = 'GET_PLACEDETAIL_ING';
export const GET_PLACEDETAIL_SUCCESS = 'GET_PLACEDETAIL_SUCCESS';
export const GET_PLACEDETAIL_FAIL = 'GET_PLACEDETAIL_FAIL';

export const GET_REVIEW_ING = 'GET_REVIEW_ING';
export const GET_REVIEW_SUCCESS = 'GET_REVIEW_SUCCESS';
export const GET_REVIEW_FAIL = 'GET_REVIEW_FAIL';

export const GET_USERPIN_ING = 'GET_USERPIN_ING';
export const GET_USERPIN_SUCCESS = 'GET_USERPIN_SUCCESS';
export const GET_USERPIN_FAIL = 'GET_USERPIN_FAIL';
